# A YAML configuration file centralizes all experiment settings
#   such as dataset paths, hyperparameters, model architecture choices,
#   logging options, and output locations, so training runs are reproducible,
#   configurable, and don't require code changes for each experiment.
#   You can change the YAML file with new hyperparameters - and run the same code again.
#     (or create a new YAML file to keep track of past experiments' hyperparams)

training:
  batch_size: 32
  epochs: 30

model:
  dropout: 0.5

optimizer:
  type: Adam
  learning_rate: 0.001

loss:
  type: BCELoss

reproducibility:
  random_state: 1

checkpointing:
  model_name: smile.pt
  model_weights: smile-weights.pt


dataset:
  num_workers: 4
  image_dir: data/images
  attributes_file: data/celeba_attr.csv
  target_name: Smiling
  train_size: 16000
  valid_size: 1000
  test_size: 10000